### ISSUE TITLE
ProSeries: Anivia Progress

### ISSUE THREAD

**Issue by xKurisu** [xKurisu/ProSeries#1]
- [x] Create Repository
- [x] Menu/Base/SkinChanger
- [x] Basic Combo
- [x] E -> R Combo
- [x] Q Logic (Prediction, Detonate, etc)
- [x] Q Anti-Gapcloser (Basic)
- [x] Auto Q CC'd (Smart Chain CC)
- [ ] Smart R Toggling
- [ ] W Logic (Advanced)
- [ ] Reducing Q Usage (Smarter Q)

**Comment by N1ghtMoon** [comment]
Auto Buy Blue Tracker In Lv9
QW/WQ Combo logic (before lv6 combo logic)
suggest if have more target have passive can double e damage, first cast to AD or AP(check)
